### ISSUE TITLE
js: trailing semicolon vs. no semicolon

### ISSUE THREAD

**Issue by LinusU** [outsideris/popularconvention#59]
I think that it would be really interesting to compare trailing semicolon vs. no semicolon, especially considering the debate in feross/standard#5.

Personally, I use popular convention whenever I don't have a really strong opinion with good arguments. The only argument for not putting semicolons seems to be "because you don't have to" (which of course can be enough of an argument).

**Comment by mattdesl** [comment]
> The only argument for not putting semicolons seems to be "because you don't have to" (which of course can be enough of an argument).

To me, it's superfluous keystrokes and clutter, and semicolon-related lint errors distract from actual problems.


I agree, this would be interesting to compare. :smile: Although I'm sure we all know which is more popular.

**Comment by outsideris** [comment]
See #55 
Also, I don't aggregate more convention data. Please refer a notice on website.
