### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by yangzj1992** [outsideris/popularconvention#67]
Visiting http://sideeffect.kr/popularconvention results in a 502 Bad Gateway error from nginx. Can you fix it?

**Comment by outsideris** [comment]
Sorry, now I can't manage the server. So, I'm working on moving the server to another server. Please wait.

**Comment by alexilyaev** [comment]
@outsideris May I suggest you'd use [now](https://zeit.co/now)?

It's got an unlimited free option and it's awesome.

**Comment by outsideris** [comment]
I recovered Popular Coding Convention on Github. http://sideeffect.kr/popularconvention Thank you for patience. If you encounter 502 error, you should wait for DNS propagation.
